<?php
/**
 * Background process launcher for the Parallel Reindexer plugin.
 *
 * Called by SystemUtils::startBackgroundProcess() from the admin UI.
 * Launches the Java parallel_reindexer.jar as a subprocess and streams
 * its output back into the BackgroundProcess notes for live monitoring.
 *
 * Usage (called automatically by the framework):
 *   php parallelReindex.php <serverName> <backgroundProcessId> [workerThreads] [mode]
 *
 * @author ByWater Solutions (BWS)
 */

require_once __DIR__ . '/../bootstrap.php';
require_once __DIR__ . '/../bootstrap_aspen.php';
require_once ROOT_DIR . '/sys/Administration/BackgroundProcess.php';

// -- Parse arguments --
$backgroundProcess = null;
if ($argc > 2) {
	$backgroundProcessId = $argv[2];
	$backgroundProcess = new BackgroundProcess();
	$backgroundProcess->id = $backgroundProcessId;
	if (!$backgroundProcess->find(true)) {
		echo("Could not find the specified background process\n");
		die();
	} elseif (!$backgroundProcess->isRunning) {
		$backgroundProcess->addNote('Error: attempted to restart previously completed background process');
		die();
	}
}

$workerThreads = 4;
if ($argc > 3 && is_numeric($argv[3])) {
	$workerThreads = intval($argv[3]);
}

$mode = 'full';
if ($argc > 4) {
	$validModes = ['full', 'fullNoClear', 'nightly'];
	if (in_array($argv[4], $validModes)) {
		$mode = $argv[4];
	}
}

logMessage("Starting Parallel Reindex with $workerThreads threads in '$mode' mode", $backgroundProcess);

// Stop all other indexers and disable auto-restart cron
logMessage("Stopping background indexers to dedicate resources...", $backgroundProcess);
stopBackgroundIndexers($backgroundProcess);

// -- Locate the parallel reindexer --
$aspenRoot = realpath(__DIR__ . '/../../..');
$parallelReindexerDir = $aspenRoot . '/code/parallel_reindexer';
$parallelReindexerJar = $parallelReindexerDir . '/parallel_reindexer.jar';
$reindexerJar = $aspenRoot . '/code/reindexer/reindexer.jar';
$normalizerJar = $aspenRoot . '/code/reindexer/lib/normalizer.jar';
$sharedLibDir = $aspenRoot . '/code/java_shared_libraries';

// Check if JAR exists
if (!file_exists($parallelReindexerJar)) {
	finish("Error: parallel_reindexer.jar not found at $parallelReindexerJar. Please build it first.", $backgroundProcess);
}

if (!file_exists($reindexerJar)) {
	finish("Error: reindexer.jar not found at $reindexerJar", $backgroundProcess);
}

// -- Write a temporary properties file with the user's thread count --
$tempPropsFile = $parallelReindexerDir . '/parallel_reindexer.properties.tmp';
$propsContent = "# Auto-generated by admin UI on " . date('Y-m-d H:i:s') . "\n";
$propsContent .= "workerThreadCount=$workerThreads\n";
$propsContent .= "solrClientThreadCount=$workerThreads\n";
$propsContent .= "solrQueueSize=" . ($workerThreads * 50) . "\n";
$propsContent .= "workQueueCapacity=10000\n";
$propsContent .= "progressReportInterval=10000\n";

// Read existing properties file and merge (user settings take precedence for non-thread settings)
$existingPropsFile = $parallelReindexerDir . '/parallel_reindexer.properties';
if (file_exists($existingPropsFile)) {
	$existingProps = parse_ini_file($existingPropsFile);
	if ($existingProps) {
		foreach ($existingProps as $key => $value) {
			// Don't override thread-related settings from the UI
			if (!in_array($key, ['workerThreadCount', 'solrClientThreadCount', 'solrQueueSize'])) {
				$propsContent .= "$key=$value\n";
			}
		}
	}
}
file_put_contents($tempPropsFile, $propsContent);

// -- Build classpath --
$classpath = $parallelReindexerJar;
$classpath .= ':' . $reindexerJar;
if (file_exists($normalizerJar)) {
	$classpath .= ':' . $normalizerJar;
}

// Shared library JARs
$sharedJars = glob($sharedLibDir . '/*.jar');
foreach ($sharedJars as $jar) {
	$classpath .= ':' . $jar;
}

// Solr JARs — check common locations
$solrLocations = [
	$aspenRoot . '/sites/default/solr-8.11.2/dist',
	'/usr/local/aspen-discovery/sites/default/solr-8.11.2/dist',
	'/opt/aspen-discovery/sites/default/solr-8.11.2/dist',
];

$solrDist = null;
foreach ($solrLocations as $loc) {
	if (is_dir($loc)) {
		$solrDist = $loc;
		break;
	}
}

if ($solrDist) {
	$solrJars = glob($solrDist . '/*.jar');
	foreach ($solrJars as $jar) {
		$classpath .= ':' . $jar;
	}
	$solrJLibJars = glob($solrDist . '/solrj-lib/*.jar');
	foreach ($solrJLibJars as $jar) {
		$classpath .= ':' . $jar;
	}
} else {
	logMessage("Warning: Could not find Solr JARs directory. The reindexer may fail.", $backgroundProcess);
}

// -- Build and run the Java command --
global $serverName;
$javaHeap = '-Xmx2g -Xms1g';
if ($workerThreads >= 8) {
	$javaHeap = '-Xmx4g -Xms2g';
}

$javaCmd = "java $javaHeap -cp " . escapeshellarg($classpath)
	. ' com.bws.aspen.parallel_reindexer.ParallelReindexMain'
	. ' ' . escapeshellarg($serverName)
	. ' ' . escapeshellarg($mode);

logMessage("Launching: $javaCmd", $backgroundProcess);

// Run the process and capture output
$descriptors = [
	0 => ['pipe', 'r'],   // stdin
	1 => ['pipe', 'w'],   // stdout
	2 => ['pipe', 'w'],   // stderr
];

$env = ['JAVA_TOOL_OPTIONS' => ''];
$process = proc_open($javaCmd, $descriptors, $pipes, $parallelReindexerDir, $env);

if (!is_resource($process)) {
	finish("Error: Failed to start Java process", $backgroundProcess);
}

fclose($pipes[0]); // Close stdin

// Make stdout and stderr non-blocking
stream_set_blocking($pipes[1], false);
stream_set_blocking($pipes[2], false);

$lastUpdateTime = time();
$outputBuffer = '';
$lineCount = 0;

// Read output in a loop, updating the background process periodically
while (true) {
	$stdout = fgets($pipes[1]);
	$stderr = fgets($pipes[2]);

	$hasOutput = false;

	if ($stdout !== false && $stdout !== '') {
		$outputBuffer .= $stdout;
		$hasOutput = true;
		$lineCount++;
	}
	if ($stderr !== false && $stderr !== '') {
		$outputBuffer .= '[ERR] ' . $stderr;
		$hasOutput = true;
		$lineCount++;
	}

	// Update background process notes every 10 seconds or every 50 lines
	$now = time();
	if (($now - $lastUpdateTime >= 10 || $lineCount >= 50) && !empty($outputBuffer)) {
		logMessage(trim($outputBuffer), $backgroundProcess);
		$outputBuffer = '';
		$lineCount = 0;
		$lastUpdateTime = $now;
	}

	// Check if process has ended
	$status = proc_get_status($process);
	if (!$status['running']) {
		// Drain remaining output
		while (($line = fgets($pipes[1])) !== false) {
			$outputBuffer .= $line;
		}
		while (($line = fgets($pipes[2])) !== false) {
			$outputBuffer .= '[ERR] ' . $line;
		}
		if (!empty($outputBuffer)) {
			logMessage(trim($outputBuffer), $backgroundProcess);
		}
		break;
	}

	// Small sleep to avoid busy-waiting
	if (!$hasOutput) {
		usleep(100000); // 100ms
	}
}

fclose($pipes[1]);
fclose($pipes[2]);

$exitCode = proc_close($process);

// Clean up temp properties file
if (file_exists($tempPropsFile)) {
	unlink($tempPropsFile);
}

// Re-enable background indexers
logMessage("Re-enabling background indexers...", $backgroundProcess);
startBackgroundIndexers($backgroundProcess);

if ($exitCode === 0) {
	finish("Parallel reindex completed successfully (exit code 0)", $backgroundProcess);
} else {
	finish("Parallel reindex finished with exit code $exitCode", $backgroundProcess);
}

// -- Helper functions --

function logMessage(string $message, ?BackgroundProcess $backgroundProcess): void {
	echo $message . "\n";
	if ($backgroundProcess !== null) {
		$backgroundProcess->addNote(date('H:i:s') . ' - ' . $message);
	}
}

function finish(string $message, ?BackgroundProcess $backgroundProcess): void {
	echo $message . "\n";
	if ($backgroundProcess !== null) {
		$backgroundProcess->endProcess($message);
	}
	die();
}

function stopBackgroundIndexers(?BackgroundProcess $backgroundProcess): void {
	exec("crontab -l 2>/dev/null", $cronLines, $rc);
	if ($rc === 0) {
		$modified = false;
		foreach ($cronLines as &$line) {
			if (strpos($line, 'checkBackgroundProcesses') !== false && strpos($line, '# TURBO_DISABLED') === false) {
				$line = '# TURBO_DISABLED ' . $line;
				$modified = true;
			}
		}
		unset($line);
		if ($modified) {
			$tmpFile = tempnam(sys_get_temp_dir(), 'cron');
			file_put_contents($tmpFile, implode("\n", $cronLines) . "\n");
			exec("crontab $tmpFile 2>&1");
			unlink($tmpFile);
			logMessage("Disabled indexer auto-restart cron", $backgroundProcess);
		}
	}

	exec("ps -eo pid,args 2>/dev/null | grep 'java.*\\.jar' | grep -v grep | grep -v TurboMigration | grep -v ParallelReindex", $processes);
	$killed = 0;
	foreach ($processes as $proc) {
		$proc = trim($proc);
		if (preg_match('/^(\d+)\s+/', $proc, $m)) {
			exec("kill " . $m[1] . " 2>/dev/null");
			$killed++;
		}
	}
	if ($killed > 0) {
		logMessage("Stopped $killed background indexer process(es)", $backgroundProcess);
	}
	sleep(2);
}

function startBackgroundIndexers(?BackgroundProcess $backgroundProcess): void {
	exec("crontab -l 2>/dev/null", $cronLines, $rc);
	if ($rc === 0) {
		$modified = false;
		foreach ($cronLines as &$line) {
			if (strpos($line, '# TURBO_DISABLED ') !== false) {
				$line = str_replace('# TURBO_DISABLED ', '', $line);
				$modified = true;
			}
		}
		unset($line);
		if ($modified) {
			$tmpFile = tempnam(sys_get_temp_dir(), 'cron');
			file_put_contents($tmpFile, implode("\n", $cronLines) . "\n");
			exec("crontab $tmpFile 2>&1");
			unlink($tmpFile);
			logMessage("Re-enabled indexer auto-restart cron", $backgroundProcess);
		}
	}

	global $serverName;
	$checkScript = '/usr/local/aspen-discovery/docker/files/cron/checkBackgroundProcessesDocker.php';
	if (file_exists($checkScript)) {
		exec("sudo -u www-data php $checkScript $serverName > /dev/null 2>&1 &");
		logMessage("Triggered indexer restart", $backgroundProcess);
	}
}
